# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity_requirements.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='entity_requirements.proto',
  package='dts',
  serialized_pb='\n\x19\x65ntity_requirements.proto\x12\x03\x64ts\";\n\x0cRequirements\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\x0e\n\x06length\x18\x02 \x02(\x05\x12\r\n\x05value\x18\x03 \x02(\tB\x12\n\x10\x62r.ufu.mehar.dts')




_REQUIREMENTS = _descriptor.Descriptor(
  name='Requirements',
  full_name='dts.Requirements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='dts.Requirements.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='dts.Requirements.length', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='dts.Requirements.value', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['Requirements'] = _REQUIREMENTS

class Requirements(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUIREMENTS

  # @@protoc_insertion_point(class_scope:dts.Requirements)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\020br.ufu.mehar.dts')
# @@protoc_insertion_point(module_scope)
