/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufu_facom_network_dlontology_FinSocket */

#ifndef _Included_br_ufu_facom_network_dlontology_FinSocket
#define _Included_br_ufu_facom_network_dlontology_FinSocket
#ifdef __cplusplus
extern "C" {
#endif
#undef br_ufu_facom_network_dlontology_FinSocket_MAX_FRAME_SIZE
#define br_ufu_facom_network_dlontology_FinSocket_MAX_FRAME_SIZE 1500L
/*
 * Class:     br_ufu_facom_network_dlontology_FinSocket
 * Method:    finOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufu_facom_network_dlontology_FinSocket_finOpen
  (JNIEnv *, jobject);

/*
 * Class:     br_ufu_facom_network_dlontology_FinSocket
 * Method:    finClose
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_br_ufu_facom_network_dlontology_FinSocket_finClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufu_facom_network_dlontology_FinSocket
 * Method:    finWrite
 * Signature: (I[BII)Z
 */
JNIEXPORT jboolean JNICALL Java_br_ufu_facom_network_dlontology_FinSocket_finWrite
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     br_ufu_facom_network_dlontology_FinSocket
 * Method:    finRead
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_br_ufu_facom_network_dlontology_FinSocket_finRead
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     br_ufu_facom_network_dlontology_FinSocket
 * Method:    setPromiscousMode
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_br_ufu_facom_network_dlontology_FinSocket_setPromiscousMode
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     br_ufu_facom_network_dlontology_FinSocket
 * Method:    getNetIfs
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_br_ufu_facom_network_dlontology_FinSocket_getNetIfs
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
