# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dtscp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import etcp_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dtscp.proto',
  package='dts',
  serialized_pb='\n\x0b\x64tscp.proto\x12\x03\x64ts\x1a\netcp.proto\"*\n\x0fWorkspaceLookup\x12\x17\n\x0fworkspace_title\x18\x01 \x02(\t\"\xbf\x01\n\x12WorkspaceAdvertise\x12\x17\n\x0fworkspace_title\x18\x01 \x02(\t\x12\x12\n\ndtsa_title\x18\x02 \x02(\t\x12\x38\n\toperation\x18\x03 \x02(\x0e\x32%.dts.WorkspaceAdvertise.OperationType\x12\r\n\x05level\x18\x04 \x02(\r\"3\n\rOperationType\x12\n\n\x06INSERT\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x12\n\n\x06UPDATE\x10\x02\"4\n\x0c\x44TSARegister\x12\r\n\x05title\x18\x01 \x02(\t\x12\x15\n\rneighborTitle\x18\x02 \x03(\t\"\xae\x02\n\x0b\x44TSAMessage\x12\x31\n\x0bmessageType\x18\x01 \x02(\x0e\x32\x1c.dts.DTSAMessage.MessageType\x12\x13\n\x0boperationId\x18\x02 \x02(\r\x12\x10\n\x08srcTitle\x18\x03 \x02(\t\x12#\n\x06\x65ntity\x18\x04 \x01(\x0b\x32\x13.dts.EntityRegister\x12\'\n\tworkspace\x18\x05 \x01(\x0b\x32\x14.dts.WorkspaceCreate\x12\x1b\n\x13poaCandidateAddress\x18\x06 \x01(\t\"Z\n\x0bMessageType\x12\x1d\n\x19\x45NTITY_HO_Candidate_Query\x10\x00\x12\x14\n\x10\x45NTITY_HO_Commit\x10\x01\x12\x16\n\x12\x45NTITY_HO_Complete\x10\x02\x42\x12\n\x10\x62r.ufu.mehar.dts')



_WORKSPACEADVERTISE_OPERATIONTYPE = _descriptor.EnumDescriptor(
  name='OperationType',
  full_name='dts.WorkspaceAdvertise.OperationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INSERT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=217,
  serialized_end=268,
)

_DTSAMESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='dts.DTSAMessage.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ENTITY_HO_Candidate_Query', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTITY_HO_Commit', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTITY_HO_Complete', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=537,
  serialized_end=627,
)


_WORKSPACELOOKUP = _descriptor.Descriptor(
  name='WorkspaceLookup',
  full_name='dts.WorkspaceLookup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace_title', full_name='dts.WorkspaceLookup.workspace_title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=74,
)


_WORKSPACEADVERTISE = _descriptor.Descriptor(
  name='WorkspaceAdvertise',
  full_name='dts.WorkspaceAdvertise',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace_title', full_name='dts.WorkspaceAdvertise.workspace_title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtsa_title', full_name='dts.WorkspaceAdvertise.dtsa_title', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operation', full_name='dts.WorkspaceAdvertise.operation', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='dts.WorkspaceAdvertise.level', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WORKSPACEADVERTISE_OPERATIONTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=77,
  serialized_end=268,
)


_DTSAREGISTER = _descriptor.Descriptor(
  name='DTSARegister',
  full_name='dts.DTSARegister',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='dts.DTSARegister.title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neighborTitle', full_name='dts.DTSARegister.neighborTitle', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=270,
  serialized_end=322,
)


_DTSAMESSAGE = _descriptor.Descriptor(
  name='DTSAMessage',
  full_name='dts.DTSAMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageType', full_name='dts.DTSAMessage.messageType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operationId', full_name='dts.DTSAMessage.operationId', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='srcTitle', full_name='dts.DTSAMessage.srcTitle', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity', full_name='dts.DTSAMessage.entity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='workspace', full_name='dts.DTSAMessage.workspace', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='poaCandidateAddress', full_name='dts.DTSAMessage.poaCandidateAddress', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DTSAMESSAGE_MESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=325,
  serialized_end=627,
)

_WORKSPACEADVERTISE.fields_by_name['operation'].enum_type = _WORKSPACEADVERTISE_OPERATIONTYPE
_WORKSPACEADVERTISE_OPERATIONTYPE.containing_type = _WORKSPACEADVERTISE;
_DTSAMESSAGE.fields_by_name['messageType'].enum_type = _DTSAMESSAGE_MESSAGETYPE
_DTSAMESSAGE.fields_by_name['entity'].message_type = etcp_pb2._ENTITYREGISTER
_DTSAMESSAGE.fields_by_name['workspace'].message_type = etcp_pb2._WORKSPACECREATE
_DTSAMESSAGE_MESSAGETYPE.containing_type = _DTSAMESSAGE;
DESCRIPTOR.message_types_by_name['WorkspaceLookup'] = _WORKSPACELOOKUP
DESCRIPTOR.message_types_by_name['WorkspaceAdvertise'] = _WORKSPACEADVERTISE
DESCRIPTOR.message_types_by_name['DTSARegister'] = _DTSAREGISTER
DESCRIPTOR.message_types_by_name['DTSAMessage'] = _DTSAMESSAGE

class WorkspaceLookup(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORKSPACELOOKUP

  # @@protoc_insertion_point(class_scope:dts.WorkspaceLookup)

class WorkspaceAdvertise(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORKSPACEADVERTISE

  # @@protoc_insertion_point(class_scope:dts.WorkspaceAdvertise)

class DTSARegister(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DTSAREGISTER

  # @@protoc_insertion_point(class_scope:dts.DTSARegister)

class DTSAMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DTSAMESSAGE

  # @@protoc_insertion_point(class_scope:dts.DTSAMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\020br.ufu.mehar.dts')
# @@protoc_insertion_point(module_scope)
