# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etcp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import entity_requirements_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='etcp.proto',
  package='dts',
  serialized_pb='\n\netcp.proto\x12\x03\x64ts\x1a\x19\x65ntity_requirements.proto\"\x8b\x01\n\x0e\x45ntityRegister\x12\r\n\x05title\x18\x01 \x02(\t\x12\'\n\x0crequirements\x18\x02 \x03(\x0b\x32\x11.dts.Requirements\x12\'\n\x0c\x63\x61pabilities\x18\x03 \x03(\x0b\x32\x11.dts.Requirements\x12\x18\n\x10\x62oundEntityTtile\x18\x04 \x01(\t\"!\n\x10\x45ntityUnregister\x12\r\n\x05title\x18\x01 \x02(\t\"\xad\x01\n\x0fWorkspaceCreate\x12\x17\n\x0fworkspace_title\x18\x01 \x02(\t\x12\x14\n\x0c\x65ntity_title\x18\x02 \x01(\t\x12\x12\n\nattach_too\x18\x03 \x01(\x08\x12\x10\n\x05level\x18\x04 \x01(\x05:\x01\x33\x12\x1c\n\rpublic_access\x18\x05 \x01(\x08:\x05\x66\x61lse\x12\'\n\x0c\x63\x61pabilities\x18\x06 \x03(\x0b\x32\x11.dts.Requirements\"@\n\x0fWorkspaceAttach\x12\x17\n\x0fworkspace_title\x18\x01 \x02(\t\x12\x14\n\x0c\x65ntity_title\x18\x02 \x02(\t\"@\n\x0fWorkspaceDetach\x12\x17\n\x0fworkspace_title\x18\x01 \x02(\t\x12\x14\n\x0c\x65ntity_title\x18\x02 \x02(\t\" \n\x0fWorkspaceDelete\x12\r\n\x05title\x18\x01 \x02(\t\"\xad\x01\n\x0fWorkspaceModify\x12\x17\n\x0fworkspace_title\x18\x01 \x02(\t\x12\x14\n\x0c\x65ntity_title\x18\x02 \x01(\t\x12\x12\n\nattach_too\x18\x03 \x01(\x08\x12\x10\n\x05level\x18\x04 \x02(\x05:\x01\x33\x12\x1c\n\rpublic_access\x18\x05 \x02(\x08:\x05\x66\x61lse\x12\'\n\x0c\x63\x61pabilities\x18\x06 \x03(\x0b\x32\x11.dts.RequirementsB\x12\n\x10\x62r.ufu.mehar.dts')




_ENTITYREGISTER = _descriptor.Descriptor(
  name='EntityRegister',
  full_name='dts.EntityRegister',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='dts.EntityRegister.title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requirements', full_name='dts.EntityRegister.requirements', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='capabilities', full_name='dts.EntityRegister.capabilities', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boundEntityTtile', full_name='dts.EntityRegister.boundEntityTtile', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=186,
)


_ENTITYUNREGISTER = _descriptor.Descriptor(
  name='EntityUnregister',
  full_name='dts.EntityUnregister',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='dts.EntityUnregister.title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=188,
  serialized_end=221,
)


_WORKSPACECREATE = _descriptor.Descriptor(
  name='WorkspaceCreate',
  full_name='dts.WorkspaceCreate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace_title', full_name='dts.WorkspaceCreate.workspace_title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity_title', full_name='dts.WorkspaceCreate.entity_title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attach_too', full_name='dts.WorkspaceCreate.attach_too', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='dts.WorkspaceCreate.level', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public_access', full_name='dts.WorkspaceCreate.public_access', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='capabilities', full_name='dts.WorkspaceCreate.capabilities', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=224,
  serialized_end=397,
)


_WORKSPACEATTACH = _descriptor.Descriptor(
  name='WorkspaceAttach',
  full_name='dts.WorkspaceAttach',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace_title', full_name='dts.WorkspaceAttach.workspace_title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity_title', full_name='dts.WorkspaceAttach.entity_title', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=399,
  serialized_end=463,
)


_WORKSPACEDETACH = _descriptor.Descriptor(
  name='WorkspaceDetach',
  full_name='dts.WorkspaceDetach',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace_title', full_name='dts.WorkspaceDetach.workspace_title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity_title', full_name='dts.WorkspaceDetach.entity_title', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=465,
  serialized_end=529,
)


_WORKSPACEDELETE = _descriptor.Descriptor(
  name='WorkspaceDelete',
  full_name='dts.WorkspaceDelete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='dts.WorkspaceDelete.title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=531,
  serialized_end=563,
)


_WORKSPACEMODIFY = _descriptor.Descriptor(
  name='WorkspaceModify',
  full_name='dts.WorkspaceModify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace_title', full_name='dts.WorkspaceModify.workspace_title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity_title', full_name='dts.WorkspaceModify.entity_title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attach_too', full_name='dts.WorkspaceModify.attach_too', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='dts.WorkspaceModify.level', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public_access', full_name='dts.WorkspaceModify.public_access', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='capabilities', full_name='dts.WorkspaceModify.capabilities', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=566,
  serialized_end=739,
)

_ENTITYREGISTER.fields_by_name['requirements'].message_type = entity_requirements_pb2._REQUIREMENTS
_ENTITYREGISTER.fields_by_name['capabilities'].message_type = entity_requirements_pb2._REQUIREMENTS
_WORKSPACECREATE.fields_by_name['capabilities'].message_type = entity_requirements_pb2._REQUIREMENTS
_WORKSPACEMODIFY.fields_by_name['capabilities'].message_type = entity_requirements_pb2._REQUIREMENTS
DESCRIPTOR.message_types_by_name['EntityRegister'] = _ENTITYREGISTER
DESCRIPTOR.message_types_by_name['EntityUnregister'] = _ENTITYUNREGISTER
DESCRIPTOR.message_types_by_name['WorkspaceCreate'] = _WORKSPACECREATE
DESCRIPTOR.message_types_by_name['WorkspaceAttach'] = _WORKSPACEATTACH
DESCRIPTOR.message_types_by_name['WorkspaceDetach'] = _WORKSPACEDETACH
DESCRIPTOR.message_types_by_name['WorkspaceDelete'] = _WORKSPACEDELETE
DESCRIPTOR.message_types_by_name['WorkspaceModify'] = _WORKSPACEMODIFY

class EntityRegister(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITYREGISTER

  # @@protoc_insertion_point(class_scope:dts.EntityRegister)

class EntityUnregister(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITYUNREGISTER

  # @@protoc_insertion_point(class_scope:dts.EntityUnregister)

class WorkspaceCreate(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORKSPACECREATE

  # @@protoc_insertion_point(class_scope:dts.WorkspaceCreate)

class WorkspaceAttach(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORKSPACEATTACH

  # @@protoc_insertion_point(class_scope:dts.WorkspaceAttach)

class WorkspaceDetach(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORKSPACEDETACH

  # @@protoc_insertion_point(class_scope:dts.WorkspaceDetach)

class WorkspaceDelete(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORKSPACEDELETE

  # @@protoc_insertion_point(class_scope:dts.WorkspaceDelete)

class WorkspaceModify(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORKSPACEMODIFY

  # @@protoc_insertion_point(class_scope:dts.WorkspaceModify)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\020br.ufu.mehar.dts')
# @@protoc_insertion_point(module_scope)
