# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dts.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import etcp_pb2
import dtscp_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dts.proto',
  package='dts',
  serialized_pb='\n\tdts.proto\x12\x03\x64ts\x1a\netcp.proto\x1a\x0b\x64tscp.proto\"\x96\x03\n\x0e\x43ontrolRequest\x12-\n\x04type\x18\x01 \x02(\x0e\x32\x1f.dts.ControlRequest.RequestType\x12\n\n\x02id\x18\x02 \x01(\x04\x12\x10\n\x08\x64stTitle\x18\x03 \x01(\t\"\xb6\x02\n\x0bRequestType\x12\x18\n\x14\x45TCP_ENTITY_REGISTER\x10\x00\x12\x1a\n\x16\x45TCP_ENTITY_UNREGISTER\x10\x01\x12\x19\n\x15\x45TCP_WORKSPACE_CREATE\x10\x02\x12\x19\n\x15\x45TCP_WORKSPACE_ATTACH\x10\x03\x12\x19\n\x15\x45TCP_WORKSPACE_DETACH\x10\x04\x12\x19\n\x15\x45TCP_WORKSPACE_DELETE\x10\x05\x12\x19\n\x15\x45TCP_WORKSPACE_MODIFY\x10\x06\x12\x1a\n\x16\x44TSCP_WORKSPACE_LOOKUP\x10\x07\x12\x1d\n\x19\x44TSCP_WORKSPACE_ADVERTISE\x10\x08\x12\x17\n\x13\x44TSCP_DTSA_REGISTER\x10\t\x12\x16\n\x12\x44TSCP_DSTA_MESSAGE\x10\n\"\x94\x01\n\x0f\x43ontrolResponse\x12\x31\n\x06status\x18\x01 \x02(\x0e\x32!.dts.ControlResponse.ReturnStatus\x12\x12\n\nrequest_id\x18\x02 \x01(\x04\x12\x10\n\x08srcTitle\x18\x03 \x01(\t\"(\n\x0cReturnStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x42\x12\n\x10\x62r.ufu.mehar.dts')



_CONTROLREQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='dts.ControlRequest.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ETCP_ENTITY_REGISTER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ETCP_ENTITY_UNREGISTER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ETCP_WORKSPACE_CREATE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ETCP_WORKSPACE_ATTACH', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ETCP_WORKSPACE_DETACH', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ETCP_WORKSPACE_DELETE', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ETCP_WORKSPACE_MODIFY', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DTSCP_WORKSPACE_LOOKUP', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DTSCP_WORKSPACE_ADVERTISE', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DTSCP_DTSA_REGISTER', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DTSCP_DSTA_MESSAGE', index=10, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=140,
  serialized_end=450,
)

_CONTROLRESPONSE_RETURNSTATUS = _descriptor.EnumDescriptor(
  name='ReturnStatus',
  full_name='dts.ControlResponse.ReturnStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=561,
  serialized_end=601,
)


_CONTROLREQUEST = _descriptor.Descriptor(
  name='ControlRequest',
  full_name='dts.ControlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='dts.ControlRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='dts.ControlRequest.id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dstTitle', full_name='dts.ControlRequest.dstTitle', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTROLREQUEST_REQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=44,
  serialized_end=450,
)


_CONTROLRESPONSE = _descriptor.Descriptor(
  name='ControlResponse',
  full_name='dts.ControlResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='dts.ControlResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='dts.ControlResponse.request_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='srcTitle', full_name='dts.ControlResponse.srcTitle', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTROLRESPONSE_RETURNSTATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=453,
  serialized_end=601,
)

_CONTROLREQUEST.fields_by_name['type'].enum_type = _CONTROLREQUEST_REQUESTTYPE
_CONTROLREQUEST_REQUESTTYPE.containing_type = _CONTROLREQUEST;
_CONTROLRESPONSE.fields_by_name['status'].enum_type = _CONTROLRESPONSE_RETURNSTATUS
_CONTROLRESPONSE_RETURNSTATUS.containing_type = _CONTROLRESPONSE;
DESCRIPTOR.message_types_by_name['ControlRequest'] = _CONTROLREQUEST
DESCRIPTOR.message_types_by_name['ControlResponse'] = _CONTROLRESPONSE

class ControlRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLREQUEST

  # @@protoc_insertion_point(class_scope:dts.ControlRequest)

class ControlResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLRESPONSE

  # @@protoc_insertion_point(class_scope:dts.ControlResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\020br.ufu.mehar.dts')
# @@protoc_insertion_point(module_scope)
